# Catppuccin Mocha — Glass Minimalism

background-color=#1e1e2ecc
text-color=#cdd6f4
border-color=#00000000
border-size=0
border-radius=12
progress-color=over #313244aa

[urgency=high]
border-color=#00000000
background-color=#1e1e2eee
