return {
  "utilyre/barbecue.nvim",
  name = "barbecue",
  version = "*",
  dependencies = {
    "SmiteshP/nvim-navic",
    "nvim-tree/nvim-web-devicons",
  },
  opts = {
    theme = "auto",
    show_modified = true,
    kinds = {
      File = "󰈙 ",
      Module = "󰆧 ",
      Namespace = "󰅪 ",
      Package = "󰏗 ",
      Class = "󰌗 ",
      Method = "󰆧 ",
      Property = "󰜢 ",
      Field = "󰜢 ",
      Constructor = "󰆧 ",
      Enum = "󰒻 ",
      Interface = "󰒻 ",
      Function = "󰊕 ",
      Variable = "󰀫 ",
      Constant = "󰏿 ",
      String = "󰉾 ",
      Number = "󰎠 ",
      Boolean = "󰁂 ",
      Array = "󰅪 ",
      Object = "󰅩 ",
      Key = "󰉹 ",
      Null = "󰟢 ",
      EnumMember = "󰒻 ",
      Struct = "󰌗 ",
      Event = "󰆧 ",
      Operator = "󰆕 ",
      TypeParameter = "󰊄 ",
    },
  },
  config = function()
    require("barbecue").setup()
  end,
} 