#!/usr/bin/env bash

set -euo pipefail

# Theme & Wallpaper Switcher - Sleek Edition

THEMES_DIR="$HOME/.config/waybar/themes"
WALL_DIR_DEFAULT="$HOME/realm/builds/dotfiles/wallpapers"
WALL_DIR_ALT="$HOME/Pictures/Wallpapers"
CURRENT_WALL_LINK="$WALL_DIR_DEFAULT/current"
CONFIG="$HOME/.config/rofi/theme-menu.rasi"

# Determine wallpapers directory
if [ -d "$WALL_DIR_DEFAULT" ]; then
    WALL_DIR="$WALL_DIR_DEFAULT"
elif [ -d "$WALL_DIR_ALT" ]; then
    WALL_DIR="$WALL_DIR_ALT"
else
    WALL_DIR=""
fi

# Get available themes
get_themes() {
    ls -1 "$THEMES_DIR"/*.css 2>/dev/null | xargs -n1 basename | sed 's/\.css$//' | grep -v "^current$"
}

# Get current theme
get_current_theme() {
    if [ -L "$THEMES_DIR/current.css" ]; then
        readlink "$THEMES_DIR/current.css" | xargs basename | sed 's/\.css$//'
    else
        echo "unknown"
    fi
}

# Apply theme
set_theme() {
    local theme="$1"
    ln -sfn ~/.config/alacritty/themes/${theme}.toml ~/.config/alacritty/themes/current.toml 2>/dev/null || true
    ln -sfn ~/.config/rofi/themes/${theme}.rasi ~/.config/rofi/themes/current.rasi 2>/dev/null || true
    ln -sfn ~/.config/waybar/themes/${theme}.css ~/.config/waybar/themes/current.css 2>/dev/null || true
    ln -sfn ~/.config/hypr/themes/${theme}.conf ~/.config/hypr/themes/current.conf 2>/dev/null || true
    ln -sfn ~/.config/mako/themes/${theme}.conf ~/.config/mako/themes/current.conf 2>/dev/null || true

    # Update GTK themes for file manager (Nautilus) etc.
    [[ -f ~/.config/gtk-4.0/themes/${theme}.css ]] && cp ~/.config/gtk-4.0/themes/${theme}.css ~/.config/gtk-4.0/gtk.css
    [[ -f ~/.config/gtk-3.0/themes/${theme}.css ]] && cp ~/.config/gtk-3.0/themes/${theme}.css ~/.config/gtk-3.0/gtk.css

    # Restart GTK apps so they pick up the new CSS
    if pgrep -x nautilus >/dev/null 2>&1; then
        nautilus -q 2>/dev/null; nohup nautilus --gapplication-service >/dev/null 2>&1 &
    fi

    echo "export DOTFILES_THEME=$theme" > ~/.config/zsh/dotfiles-theme.env

    # Generate rofi layout overrides for themes with bottom bar
    local rofi_overrides="$HOME/.config/rofi/theme-overrides.rasi"
    if [[ -d ~/.config/waybar/configs/${theme} ]] && grep -q '"bottom"' ~/.config/waybar/configs/${theme}/config 2>/dev/null; then
        cat > "$rofi_overrides" << 'RASI'
/* Auto-generated by appearance switcher — bottom bar overrides */
window { location: south; anchor: south; y-offset: -10px; border-radius: 0; }
inputbar { border-radius: 0; }
listview { border-radius: 0; }
element { border-radius: 0; }
RASI
    else
        echo '/* Auto-generated by appearance switcher — no overrides */' > "$rofi_overrides"
    fi
    
    # Regenerate waybar style.css (theme colors + layout) and config
    local layout_dir="default"
    [[ -d ~/.config/waybar/configs/${theme} ]] && layout_dir="${theme}"
    if [[ -f ~/.config/waybar/themes/${theme}.css ]] && [[ -f ~/.config/waybar/configs/${layout_dir}/style.css ]]; then
        cat ~/.config/waybar/themes/${theme}.css ~/.config/waybar/configs/${layout_dir}/style.css > ~/.config/waybar/style.css
    fi
    if [[ -f ~/.config/waybar/configs/${layout_dir}/config ]]; then
        cp ~/.config/waybar/configs/${layout_dir}/config ~/.config/waybar/config
    fi
    
    pkill -SIGUSR2 waybar 2>/dev/null || killall waybar 2>/dev/null && waybar &
    makoctl reload 2>/dev/null || true
    notify-send "󰏘 Theme" "$theme" -t 2000
}

# Get rofi overrides for themes with bottom bar
get_rofi_overrides() {
    local current=$(get_current_theme)
    if [[ -d ~/.config/waybar/configs/${current} ]]; then
        local pos=$(grep -o '"position": *"[^"]*"' ~/.config/waybar/configs/${current}/config 2>/dev/null | head -1 | grep -o '"[^"]*"$' | tr -d '"')
        if [[ "$pos" == "bottom" ]]; then
            echo '-theme-str "window { location: south; anchor: south; y-offset: -10px; border-radius: 0; } element { border-radius: 0; } inputbar { border-radius: 0; } listview { border-radius: 0; }"'
        fi
    fi
}

# Show themes menu
show_themes() {
    local current=$(get_current_theme)
    local entries=""
    for theme in $(get_themes); do
        if [ "$theme" = "$current" ]; then
            entries+="󰸞  $theme\n"
        else
            entries+="󰏘  $theme\n"
        fi
    done
    entries=$(echo -e "$entries" | sed '/^$/d')

    local overrides=$(get_rofi_overrides)
    selected=$(echo -e "$entries" | eval rofi -dmenu -i -config '"$CONFIG"' $overrides)
    [ -z "$selected" ] && return

    theme_name=$(echo "$selected" | sed 's/^[^ ]* *//')
    [ "$theme_name" != "$current" ] && set_theme "$theme_name"
}

# Generate thumbnail for a wallpaper image
generate_thumbnail() {
    local src="$1"
    local thumb_dir="$HOME/.cache/wallpaper-thumbs"
    mkdir -p "$thumb_dir"
    local base
    base=$(basename "$src")
    local thumb="$thumb_dir/${base%.*}.png"

    # Regenerate if missing or older than source
    if [[ ! -f "$thumb" ]] || [[ "$src" -nt "$thumb" ]]; then
        magick "$src" -resize 200x120^ -gravity center -extent 200x120 "$thumb" 2>/dev/null || return 1
    fi
    echo "$thumb"
}

# Show wallpapers menu with thumbnail previews
show_wallpapers() {
    if [ -z "$WALL_DIR" ]; then
        notify-send "󰸉 Wallpaper" "No wallpapers directory found"
        return
    fi

    mapfile -t FILES < <(find "$WALL_DIR" -maxdepth 1 -type f \( -iname "*.jpg" -o -iname "*.jpeg" -o -iname "*.png" -o -iname "*.webp" \) | sort)

    if [ ${#FILES[@]} -eq 0 ]; then
        notify-send "󰸉 Wallpaper" "No images found"
        return
    fi

    # Get current wallpaper for marking
    local current_wall=""
    if [ -L "$CURRENT_WALL_LINK" ]; then
        current_wall=$(readlink -f "$CURRENT_WALL_LINK" 2>/dev/null)
    fi

    # Build rofi entries with thumbnail icons
    local entries=""
    for f in "${FILES[@]}"; do
        local name
        name=$(basename "$f")
        local thumb
        thumb=$(generate_thumbnail "$f")
        local mark=""
        if [[ "$(readlink -f "$f")" == "$current_wall" ]]; then
            mark="  *"
        fi
        if [[ -n "$thumb" ]]; then
            entries+="${name}${mark}\0icon\x1f${thumb}\n"
        else
            entries+="${name}${mark}\n"
        fi
    done

    local overrides=$(get_rofi_overrides)
    selected=$(echo -e "$entries" | eval rofi -dmenu -i -show-icons -config '"$CONFIG"' $overrides \
        -theme-str '"element-icon { size: 48px; margin: 0 8px 0 0; }"')
    [ -z "$selected" ] && return

    # Strip the active marker if present
    wall_name=$(echo "$selected" | sed 's/  \*$//')
    SEL_FILE="$WALL_DIR/$wall_name"

    if [[ ! -f "$SEL_FILE" ]]; then
        notify-send "󰸉 Wallpaper" "File not found: $wall_name"
        return
    fi

    # Ensure hyprpaper is running
    if ! pgrep -x hyprpaper >/dev/null 2>&1; then
        hyprpaper &
        sleep 1
    fi

    # Unload old wallpapers, preload new, apply
    hyprctl hyprpaper unload all >/dev/null 2>&1 || true
    hyprctl hyprpaper preload "$SEL_FILE" >/dev/null 2>&1 || true

    mapfile -t MONS < <(hyprctl monitors | sed -n 's/^Monitor \([^ ]*\).*/\1/p')
    for m in "${MONS[@]}"; do
        hyprctl hyprpaper wallpaper "$m,$SEL_FILE" >/dev/null 2>&1 || true
    done

    ln -sfn "$SEL_FILE" "$CURRENT_WALL_LINK"
    notify-send "󰸉 Wallpaper" "$wall_name" -t 2000
}

# Main menu
main_menu() {
    local options="󰏘  Themes\n󰸉  Wallpapers"
    local overrides=$(get_rofi_overrides)
    selected=$(echo -e "$options" | eval rofi -dmenu -i -config '"$CONFIG"' $overrides)

    case "$selected" in
        *Themes*) show_themes ;;
        *Wallpapers*) show_wallpapers ;;
    esac
}

main_menu
